"""reports update time added

Revision ID: 137a4c5c9e1a
Revises: 140bb2446cd7
Create Date: 2025-02-23 20:27:02.558761

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '137a4c5c9e1a'
down_revision = '140bb2446cd7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    # ### end Alembic commands ###
