"""reports changed

Revision ID: 140bb2446cd7
Revises: ef909096302e
Create Date: 2025-02-23 20:03:49.439102

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '140bb2446cd7'
down_revision = 'ef909096302e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.add_column(sa.Column('handled', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('handled_by', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('action', sa.String(length=20), nullable=True))
        batch_op.create_foreign_key('fk_report', 'user', ['handled_by'], ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('action')
        batch_op.drop_column('handled_by')
        batch_op.drop_column('handled')

    # ### end Alembic commands ###
