"""Views

Revision ID: 207dce70fb7a
Revises: 8c31d26bd096
Create Date: 2025-02-09 19:32:24.472497

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '207dce70fb7a'
down_revision = '8c31d26bd096'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('discussion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('views', sa.Integer(), nullable=True))

    with op.batch_alter_table('problem', schema=None) as batch_op:
        batch_op.add_column(sa.Column('views', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('problem', schema=None) as batch_op:
        batch_op.drop_column('views')

    with op.batch_alter_table('discussion', schema=None) as batch_op:
        batch_op.drop_column('views')

    # ### end Alembic commands ###
