"""Update cascade added in problems

Revision ID: 28f3f19d3c65
Revises: 5b1c0f7ec672
Create Date: 2025-03-15 21:46:35.157693

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28f3f19d3c65'
down_revision = '5b1c0f7ec672'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('problem', schema=None) as batch_op:
        batch_op.drop_constraint('problem_author_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['author'], ['username'], onupdate='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('problem', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('problem_author_fkey', 'user', ['author'], ['username'])

    # ### end Alembic commands ###
