"""flagged bool added

Revision ID: 38bae49073ea
Revises: 5c71a20c344a
Create Date: 2025-02-17 00:52:54.747683

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38bae49073ea'
down_revision = '5c71a20c344a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('flagged', sa.Boolean(), nullable=True))

    with op.batch_alter_table('discussion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('flagged', sa.Boolean(), nullable=True))

    with op.batch_alter_table('problem', schema=None) as batch_op:
        batch_op.add_column(sa.Column('flagged', sa.Boolean(), nullable=True))

    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.drop_column('comments')
        batch_op.drop_column('problems_posted')
        batch_op.drop_column('solutions')
        batch_op.drop_column('discussions')

    with op.batch_alter_table('solutions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('flagged', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solutions', schema=None) as batch_op:
        batch_op.drop_column('flagged')

    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('discussions', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('solutions', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('problems_posted', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('comments', sa.INTEGER(), nullable=True))

    with op.batch_alter_table('problem', schema=None) as batch_op:
        batch_op.drop_column('flagged')

    with op.batch_alter_table('discussion', schema=None) as batch_op:
        batch_op.drop_column('flagged')

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_column('flagged')

    # ### end Alembic commands ###
