"""Content tables added

Revision ID: 396770ff34e3
Revises: 8e60c7c32649
Create Date: 2025-02-05 18:34:26.621377

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '396770ff34e3'
down_revision = '8e60c7c32649'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('problem', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('encrypted_answer', sa.Text(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('problem', schema=None) as batch_op:
        batch_op.drop_column('encrypted_answer')
        batch_op.drop_column('content')

    # ### end Alembic commands ###
