"""Content tables added in soln

Revision ID: 4cdea552775d
Revises: 396770ff34e3
Create Date: 2025-02-05 19:29:23.319996

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4cdea552775d'
down_revision = '396770ff34e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solutions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('solution', sa.Text(), nullable=False))
        batch_op.drop_column('content_path')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solutions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content_path', sa.TEXT(), nullable=False))
        batch_op.drop_column('solution')

    # ### end Alembic commands ###
