"""Flagged by added

Revision ID: 529c866f7d2b
Revises: cda13711e0a1
Create Date: 2025-02-18 15:22:21.332778

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '529c866f7d2b'
down_revision = 'cda13711e0a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
