"""Flagged by added

Revision ID: 529c866f7d2b
Revises: cda13711e0a1
Create Date: 2025-02-18 15:22:21.332778

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '529c866f7d2b'
down_revision = 'cda13711e0a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flagged_content', schema=None) as batch_op:
        batch_op.add_column(sa.Column('flagged_by', sa.String(length=10), nullable=True))
        batch_op.create_foreign_key('fk_flagged_by_moderators', 'moderators', ['flagged_by'], ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flagged_content', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('flagged_by')

    # ### end Alembic commands ###
