"""notif mod

Revision ID: 5c71a20c344a
Revises: 50640a026056
Create Date: 2025-02-13 17:38:40.983954

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c71a20c344a'
down_revision = '50640a026056'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent_id', sa.String(length=10), nullable=False))
        batch_op.alter_column('id',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Integer(),
               postgresql_using="id::integer",
               existing_nullable=False,
               autoincrement=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False,
               autoincrement=True)
        batch_op.drop_column('parent_id')

    # ### end Alembic commands ###
