"""Upvotes changed

Revision ID: 7a35661015a0
Revises: 5529264ab682
Create Date: 2025-02-08 11:21:53.961497

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a35661015a0'
down_revision = '5529264ab682'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_column('upvotes')

    with op.batch_alter_table('discussion', schema=None) as batch_op:
        batch_op.drop_column('upvotes')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('discussion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('upvotes', sa.INTEGER(), nullable=True))

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('upvotes', sa.INTEGER(), nullable=True))

    # ### end Alembic commands ###
