"""Flagged-content

Revision ID: 801e9bdc6c1e
Revises: 38bae49073ea
Create Date: 2025-02-18 14:32:26.529954

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '801e9bdc6c1e'
down_revision = '38bae49073ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flagged_content',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('parent_id', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('report',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('parent_id', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('appeals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('flag_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['flag_id'], ['flagged_content.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_column('flagged')

    with op.batch_alter_table('discussion', schema=None) as batch_op:
        batch_op.drop_column('flagged')

    with op.batch_alter_table('problem', schema=None) as batch_op:
        batch_op.drop_column('flagged')

    with op.batch_alter_table('solutions', schema=None) as batch_op:
        batch_op.drop_column('flagged')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solutions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('flagged', sa.BOOLEAN(), nullable=True))

    with op.batch_alter_table('problem', schema=None) as batch_op:
        batch_op.add_column(sa.Column('flagged', sa.BOOLEAN(), nullable=True))

    with op.batch_alter_table('discussion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('flagged', sa.BOOLEAN(), nullable=True))

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('flagged', sa.BOOLEAN(), nullable=True))

    op.drop_table('appeals')
    op.drop_table('report')
    op.drop_table('flagged_content')
    # ### end Alembic commands ###
