"""moderation simplified

Revision ID: ad1054464409
Revises: d109d611c144
Create Date: 2025-02-19 00:57:10.444696

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad1054464409'
down_revision = 'd109d611c144'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('appeals')
    op.drop_table('flagged_content')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flagged_content',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('parent_id', sa.VARCHAR(length=10), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('reason', sa.VARCHAR(length=255), nullable=True),
    sa.Column('flagged_by', sa.VARCHAR(length=10), nullable=True),
    sa.ForeignKeyConstraint(['flagged_by'], ['moderators.username'], name='fk_flagged_by_moderators'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('appeals',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('flag_id', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('appeal_reason', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['flag_id'], ['flagged_content.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
