"""Flagged by added

Revision ID: cda13711e0a1
Revises: b1a54edd67e6
Create Date: 2025-02-18 15:21:09.227959

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cda13711e0a1'
down_revision = 'b1a54edd67e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appeals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('appeal_reason', sa.Text(), nullable=True))

    with op.batch_alter_table('flagged_content', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reason', sa.String(length=255), nullable=True))

    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reason', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.drop_column('reason')

    with op.batch_alter_table('flagged_content', schema=None) as batch_op:
        batch_op.drop_column('reason')

    with op.batch_alter_table('appeals', schema=None) as batch_op:
        batch_op.drop_column('appeal_reason')

    # ### end Alembic commands ###
