"""Country

Revision ID: ce7cbf15f00c
Revises: 4cdea552775d
Create Date: 2025-02-06 01:01:07.032568

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce7cbf15f00c'
down_revision = '4cdea552775d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.drop_column('country')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('country', sa.VARCHAR(length=255), nullable=True))

    # ### end Alembic commands ###
